---
title: "2D dividing and conquer"
author: "Chenghui Li"
date: "2021/2/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pacman)
p_load("dplyr","plotrix","spatstat","TDA","hitandrun","functional","Rfast","plotly","viridis","plot3D")
require(vrmlgen)
require(rgl)
require(fields)
library(pryr) # use for testing memory
source('Myfunctions/CombineD.R')
source('Myfunctions/Divide.R')
source('Myfunctions/IdentifyBoun.R')
source('Myfunctions/Myplot.R')
source('Myfunctions/HighlightBox.R')
source('Myfunctions/Death.R')
source('Myfunctions/Regularized.R')
source('Myfunctions/BoxFeatures.R')
```



```{r}
# Test for CombineD function
set.seed(2020)
signal <- circleUnif(1000,4)*rnorm(40,1,0.1)
noise <- matrix(runif(2*500,-6,18),ncol=2)
#plot(signal[,1],signal[,2])
#plot(noise[,1],noise[,2])
X <- rbind(signal,noise)
plot(X,asp=1,pch=20,cex=0.4,col=alpha("black",0.7))
draw.circle(0,0,4,border = alpha('red',0.2),lwd=3)
```

```{r}
by <- 0.5
Grid0 <- seq(-6, 18, by = by)
Grid <- expand.grid(Grid0, Grid0)
m0 <- 0.1
DTM <- dtm(X = X, Grid = Grid, m0 = m0)
Xseq <- Grid0
Yseq <- Grid0
Xdtm=matrix(DTM, ncol = length(Yseq), nrow = length(Xseq))
colnames(Xdtm)<-Yseq
rownames(Xdtm)<-Xseq

################### Use the 'divide' function to generate testing data form
by=0.5
m0=0.1
Diag1<-Divide(X,lim = matrix(c(-6,18,-6,18),2,byrow=T),n=3,by=by,m0=m0)
# Diag1 is the divided diagrams.
Diagcombine<-CombineDiagram(Diag1,tol=by)
par(mfrow=c(1,2))
one <- which(
  Diagcombine[["diagram"]][, 1] == 1 &
    Diagcombine[["diagram"]][, 3] - Diagcombine[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
#HighLightBox(X,Diag1,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
BoxFeatures(X = X,Diagcombine = Diagcombine,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
for (i in seq(along = one)) {
  points(Diagcombine[['birthLocation']][one[i],1],Diagcombine[['birthLocation']][one[i],2],col='green')
  points(Diagcombine[['deathLocation']][one[i],1],Diagcombine[['deathLocation']][one[i],2],col='blue')
  for (j in seq_len(dim(Diagcombine[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diagcombine[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
}
Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
one <- which(
  Diag3[["diagram"]][, 1] == 1 &
    Diag3[["diagram"]][, 3] - Diag3[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
plot(X,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
for (i in seq(along = one)) {
  for (j in seq_len(dim(Diag3[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diag3[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diag3[['birthLocation']][one[i],1],Diag3[['birthLocation']][one[i],2],col='green')
  points(Diag3[['deathLocation']][one[i],1],Diag3[['deathLocation']][one[i],2],col='blue')
}


# Fake band
par(mfrow=c(1,2))
Myplot(x = Diagcombine,band=1.5) # This would allow us to include the Doubt information.


# Compare with the the diagram used the whole data set.

Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
plot.diagram(x = Diag3[["diagram"]],band=1.5,main = "diagram plot")

#Compare the diagram directly
Diag3$diagram
Diagcombine$diagram
Diagcombine$Doubt
```

```{r}
############## Include new data to do the test.
# We add a small circle in 2 subboxes and 1 large circle.
set.seed(2020)
signal <- c(-1,-1)+ circleUnif(1000,3)*rnorm(40,1,0.1)
noise <- matrix(runif(2*1000,-6,18),ncol=2)
signal2 <- circleUnif(1000,6)*rnorm(40,1,0.1)+c(11,11)
signal3 <- c(3.5,3.5)+circleUnif(1000,1)*rnorm(40,1,0.1)
X <- rbind(signal,noise,signal2,signal3)
plot(X,asp=1,pch=20,cex=0.4,col=alpha("black",0.7))
draw.circle(11,11,6,border = alpha('red',0.2),lwd=3)
draw.circle(3.5,3,5,1,border = alpha('red',0.2),lwd=3)
draw.circle(-1,-1,3,border = alpha('red',0.2),lwd=3)
```

```{r}
by=0.5
m0=0.1
Diag1<-Divide(X,lim = matrix(c(-6,18,-6,18),2,byrow=T),n=3,by=by,m0=m0)
# Diag1 is the divided diagrams.
Diagcombine<-CombineDiagram(Diag1,tol=by)

par(mfrow=c(1,2))
one <- which(
  Diagcombine[["diagram"]][, 1] == 1 &
    Diagcombine[["diagram"]][, 3] - Diagcombine[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
#HighLightBox(X,Diag1,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
BoxFeatures(X = X,Diagcombine = Diagcombine,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")

for (i in seq(along = one)) {
  for (j in seq_len(dim(Diagcombine[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diagcombine[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diagcombine[['birthLocation']][one[i],1],Diagcombine[['birthLocation']][one[i],2],col='green')
  points(Diagcombine[['deathLocation']][one[i],1],Diagcombine[['deathLocation']][one[i],2],col='blue')
}

# This is based on whole dataset
Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
one <- which(
  Diag3[["diagram"]][, 1] == 1 &
    Diag3[["diagram"]][, 3] - Diag3[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
plot(X,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
for (i in seq(along = one)) {
  for (j in seq_len(dim(Diag3[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diag3[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diag3[['birthLocation']][one[i],1],Diag3[['birthLocation']][one[i],2],col='green')
  points(Diag3[['deathLocation']][one[i],1],Diag3[['deathLocation']][one[i],2],col='blue')
}

```

```{r}
# Fake band
par(mfrow=c(1,2))
Myplot(x = Diagcombine,band=1.5) # This would allow us to include the Doubt information.


# Compare with the the diagram used the whole data set.

Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
plot.diagram(x = Diag3[["diagram"]],band=1.5,main = "diagram plot")

#Compare the diagram directly
Diag3$diagram
Diagcombine$diagram
Diagcombine$Doubt
```


```{r}
#################### A huge circle

set.seed(2020)
signal <- c(6,6)+ circleUnif(1000,10)*rnorm(40,1,0.1)
noise <- matrix(runif(2*1000,-6,18),ncol=2)
X <- rbind(signal,noise)
plot(X,asp=1,pch=20,cex=0.4,col=alpha("black",0.7))
draw.circle(6,6,10,border = alpha('red',0.2),lwd=3)
```

```{r}
# test again

by=0.5
m0=0.1
Diag1<-Divide(X,lim = matrix(c(-6,18,-6,18),2,byrow=T),n=3,by=by,m0=m0)
# Diag1 is the divided diagrams.
Diagcombine<-CombineDiagram(Diag1,tol=by)

#This cannot appear because only 1 features in diagram
par(mfrow=c(1,2))
one <- which(
  Diagcombine[["diagram"]][, 1] == 1 &
    Diagcombine[["diagram"]][, 3] - Diagcombine[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
#HighLightBox(X,Diag1,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
BoxFeatures(X = X,Diagcombine = Diagcombine,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")

for (i in seq(along = one)) {
  for (j in seq_len(dim(Diagcombine[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diagcombine[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diagcombine[['birthLocation']][one[i],1],Diagcombine[['birthLocation']][one[i],2],col='green')
  points(Diagcombine[['deathLocation']][one[i],1],Diagcombine[['deathLocation']][one[i],2],col='blue')
}
Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
one <- which(
  Diag3[["diagram"]][, 1] == 1 &
    Diag3[["diagram"]][, 3] - Diag3[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
plot(X,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
for (i in seq(along = one)) {
  for (j in seq_len(dim(Diag3[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diag3[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diag3[['birthLocation']][one[i],1],Diag3[['birthLocation']][one[i],2],col='green')
  points(Diag3[['deathLocation']][one[i],1],Diag3[['deathLocation']][one[i],2],col='blue')
}


# Fake band
par(mfrow=c(1,2))
Myplot(x = Diagcombine,band=1.5) # This would allow us to include the Doubt information.


# Compare with the the diagram used the whole data set.

Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
plot.diagram(x = Diag3[["diagram"]],band=1.5,main = "diagram plot")

#Compare the diagram directly
Diag3$diagram
Diagcombine$diagram
Diagcombine$Doubt

```

Let's provide more analysis on this example because it tends to show a "shrinkage" of the loop location. We try to plot the image for dtm plot.
```{r}

```


```{r}
#################### A smaller circle

set.seed(2020)
signal <- c(6,6)+ circleUnif(1000,7)*rnorm(40,1,0.1)
noise <- matrix(runif(2*1000,-6,18),ncol=2)
X <- rbind(signal,noise)
plot(X,asp=1,pch=20,cex=0.4,col=alpha("black",0.7))
draw.circle(6,6,7,border = alpha('red',0.2),lwd=3)
```

```{r}
# test again

by=0.5
m0=0.1
Diag1<-Divide(X,lim = matrix(c(-6,18,-6,18),2,byrow=T),n=3,by=by,m0=m0)
# Diag1 is the divided diagrams.
Diagcombine<-CombineDiagram(Diag1,tol=by)

#This cannot appear because only 1 features in diagram
par(mfrow=c(1,2))
one <- which(
  Diagcombine[["diagram"]][, 1] == 1 &
    Diagcombine[["diagram"]][, 3] - Diagcombine[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
#HighLightBox(X,Diag1,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
BoxFeatures(X = X,Diagcombine = Diagcombine,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")

for (i in seq(along = one)) {
  for (j in seq_len(dim(Diagcombine[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diagcombine[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diagcombine[['birthLocation']][one[i],1],Diagcombine[['birthLocation']][one[i],2],col='green')
  points(Diagcombine[['deathLocation']][one[i],1],Diagcombine[['deathLocation']][one[i],2],col='blue')
}
Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
one <- which(
  Diag3[["diagram"]][, 1] == 1 &
    Diag3[["diagram"]][, 3] - Diag3[["diagram"]][, 2] > 0.001)# Can change to band[["width"]]
plot(X,asp=1,pch=20,cex=0.4, col = 2, main = "Representative loop of data points")
for (i in seq(along = one)) {
  for (j in seq_len(dim(Diag3[["cycleLocation"]][[one[i]]])[1])) {
    lines(
      Diag3[["cycleLocation"]][[one[i]]][j, , ], pch = 19, cex = 1,
      col = i)
  }
  points(Diag3[['birthLocation']][one[i],1],Diag3[['birthLocation']][one[i],2],col='green')
  points(Diag3[['deathLocation']][one[i],1],Diag3[['deathLocation']][one[i],2],col='blue')
}



# Fake band
par(mfrow=c(1,2))
Myplot(x = Diagcombine,band=1.5) # This would allow us to include the Doubt information.


# Compare with the the diagram used the whole data set.

Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus")
plot.diagram(x = Diag3[["diagram"]],band=1.5,main = "diagram plot")

#Compare the diagram directly
Diag3$diagram
Diagcombine$diagram
Diagcombine$Doubt

```


A simple timing test. Basically, we want to test if there is a timing difference between our dividing process and the diagram using the total data.
```{r}
# This is for the original method by using the whole data set.
signal <- c(6,6)+ circleUnif(10000,7)*rnorm(40,1,0.1)
noise <- matrix(runif(2*10000,-6,18),ncol=2)
X <- rbind(signal,noise)

system.time(Diag3<-gridDiag(X,dtm,lim=matrix(c(-6,18,-6,18),2),by=0.5,m0=0.1, sublevel = TRUE,
                printProgress = TRUE,location=T,maxdimension = 2,library="Dionysus"))

# The following is using the dividing and conquer method.
system.time({Diag1<-Divide(X,lim = matrix(c(-6,18,-6,18),2,byrow=T),n=3,by=by,m0=m0)
# Diag1 is the divided diagrams.
Diagcombine<-CombineDiagram(Diag1,tol=by)})

### And then let's test for memory information.
```
